### ISSUE TITLE
NutchPy Seq-Reader via Nutch REST Service

### ISSUE THREAD

**Issue by sujen1412** [chrismattmann/nutch-python#12]
Here is the issue for Nutchpy - https://github.com/ContinuumIO/nutchpy/issues/12

Docs for the Reader endpoint - http://docs.nutchpytonutchrestapi.apiary.io/

**Comment by sujen1412** [comment]
PR for this issue in Nutch - https://github.com/apache/nutch/pull/80

**Comment by chrismattmann** [comment]
+1 looks great in https://github.com/apache/nutch/pull/80 please commit. Then let's address it with Python code here.

**Comment by chrismattmann** [comment]
@sujen1412 is this committed? If so should we close this issue out?

cc @ahmadia

**Comment by sujen1412** [comment]
This is committed in Nutch. Have not made any changes to the python code.

**Comment by chrismattmann** [comment]
ok so that's next right @sujen1412 ?

**Comment by sujen1412** [comment]
Yup.

**Comment by chrismattmann** [comment]
closed and taken care of.

**Comment by chrismattmann** [comment]
fixed in e1c2c9ae0bf402574a237faa33c7c2a528e39cf1
