### ISSUE TITLE
update `nutch-python` usage/documentation

### ISSUE THREAD

**Issue by ahmadia** [chrismattmann/nutch-python#3]
Unfortunately I think I've left the CLI a bit behind with the last few weeks of work.  The best examples of usage are in the `test_nutch.py` file right now.  I've been waiting for the dust to settle a bit around the refactor to update the documentation but this is a reasonable time to do so.

What are the primary goals of the CLI?  Should it expose the full RESTful interface, or are there specific tasks you want to enable?  Personally, I'm a bit more interested in the Pythonic interface, but I want to make sure we keep our use cases covered.

**Comment by ayberk** [comment]
Thanks professor @chrismattmann!

I have already started working on fixing the main method and updating in-code documentation (i.e. comments). I'll make these my top priority for now, but I'd be glad to help with the future work.

**Comment by chrismattmann** [comment]
thanks @ayberk  - please submit some doc updates when you get a chance thank you!

**Comment by ahmadia** [comment]
Has this been resolved?

**Comment by chrismattmann** [comment]
hey @ayberk did you resolve this?

**Comment by ayberk** [comment]
@ahmadia @chrismattmann Unfortunately, not yet. I have mostly cleaned the out-of-date comments from the code, but haven't been able to work on fixing the command line yet.

**Comment by chrismattmann** [comment]
Hmm, @ayberk can you please send a PR for your in-progress work and we'll close this out after? Then if/when you get time to update the command line, you can open a new issue. Fair? Can you send the PR ASAP? Thanks!

cc /@ahmadia

**Comment by chrismattmann** [comment]
ping @ayberk

**Comment by ayberk** [comment]
sorry for the delay professor. I submitted the work I started (#14). I will continue working after the exams :)

**Comment by chrismattmann** [comment]
Thank you!!

**Comment by chrismattmann** [comment]
Hi @ayberk do you have any updates here?

**Comment by chrismattmann** [comment]
initial work is done here so I think we're good.
